[package]
name = "rustynes"
version = "0.1.0"
authors = ["bokuweb <bokuweb12@gmail.com>"]

[dependencies]

libc="*"
lazy_static = "1.4"
log = "0.4"
regex = "1.6"

[workspace]
members = [
    "standalone",
]
