defaults: &defaults
  working_directory: ~/rustnes
  docker:
    - image: rust
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build
          command: make     
      - run:
          name: Test
          command: |
            cargo test       
