[package]
name = "standalone"
version = "0.1.0"
authors = ["tyfkda <tyfkda@gmail.com>"]

[dependencies]
sdl2 = "0.32.2"
log = "0.4"
regex = "1.6"
rustynes = { path = ".." }

[[bin]]
name = "rustynes"
path = "src/main.rs"
